# MariaDB, PHPMyAdmin, and Apache Stack
# Apache Continer: PHP, Python, or Node.js
version: "2"
services:
    # PENDING SERVICE
    # web: 
    #   image: 
    #   container_name: 
    #   restart: always
    #   ports: 
    #       - "8888:8080"
    #   environment:
    #   volumes:
    
    mariadb:
        image: mariadb
        container_name: mariadb
        restart: always
        ports: 
            - "3306:3306"
        environment:
            # Change information as needed
            MYSQL_DATABASE: testdb
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            # - ./dump.sql:/docker-entrypoint-initdb.d
            - mariadb:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        links: 
            - mariadb
        ports:
            - 8000:80
        environment:
            # Change information as needed
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            PMA_HOST: mariadb
            PMA_PORT: 3306
        depends_on: 
        - mariadb
volumes:
    mariadb: